apiVersion: v1
kind: Namespace
metadata:
  name: hpc-system
  labels:
    name: hpc-system
    purpose: hpc-workload-optimization
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hpc-service-account
  namespace: hpc-system
automountServiceAccountToken: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: hpc-system
  name: hpc-service-role
rules:
- apiGroups: [""]
  resources: ["pods", "services", "configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["autoscaling"]
  resources: ["horizontalpodautoscalers"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: hpc-service-rolebinding
  namespace: hpc-system
subjects:
- kind: ServiceAccount
  name: hpc-service-account
  namespace: hpc-system
roleRef:
  kind: Role
  name: hpc-service-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ml-models-config
  namespace: hpc-system
data:
  model_version: "1.0.0"
  model_path: "/app/models"
  retrain_interval: "24h"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: hpc-system
data:
  log_level: "INFO"
  metrics_enabled: "true"
  health_check_interval: "30s"
  prediction_cache_ttl: "300s"
  optimization_timeout: "60s"
---
apiVersion: v1
kind: Secret
metadata:
  name: hpc-tls-secret
  namespace: hpc-system
type: kubernetes.io/tls
data:
  tls.crt: # Base64 encoded TLS certificate
  tls.key: # Base64 encoded TLS private key
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: workload-predictor-pdb
  namespace: hpc-system
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: workload-predictor
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: resource-optimizer-pdb
  namespace: hpc-system
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: resource-optimizer
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: api-gateway-pdb
  namespace: hpc-system
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: api-gateway
