apiVersion: apps/v1
kind: Deployment
metadata:
  name: resource-optimizer
  namespace: hpc-system
  labels:
    app: resource-optimizer
    tier: optimization-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: resource-optimizer
  template:
    metadata:
      labels:
        app: resource-optimizer
        tier: optimization-service
    spec:
      containers:
      - name: resource-optimizer
        image: hpc-utilization/resource-optimizer:latest
        ports:
        - containerPort: 8001
        env:
        - name: PORT
          value: "8001"
        - name: ENVIRONMENT
          value: "production"
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8001
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8001
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
        volumeMounts:
        - name: tmp
          mountPath: /tmp
      volumes:
      - name: tmp
        emptyDir: {}
      restartPolicy: Always
      serviceAccountName: hpc-service-account
---
apiVersion: v1
kind: Service
metadata:
  name: resource-optimizer-service
  namespace: hpc-system
  labels:
    app: resource-optimizer
spec:
  selector:
    app: resource-optimizer
  ports:
  - protocol: TCP
    port: 8001
    targetPort: 8001
    name: http
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: resource-optimizer-hpa
  namespace: hpc-system
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: resource-optimizer
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 75
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 85
