apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduler-optimizer
  namespace: hpc-system
  labels:
    app: scheduler-optimizer
    tier: scheduling-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: scheduler-optimizer
  template:
    metadata:
      labels:
        app: scheduler-optimizer
        tier: scheduling-service
    spec:
      containers:
      - name: scheduler-optimizer
        image: hpc-utilization/scheduler-optimizer:latest
        ports:
        - containerPort: 8002
        env:
        - name: PORT
          value: "8002"
        - name: ENVIRONMENT
          value: "production"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8002
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8002
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
        volumeMounts:
        - name: tmp
          mountPath: /tmp
      volumes:
      - name: tmp
        emptyDir: {}
      restartPolicy: Always
      serviceAccountName: hpc-service-account
---
apiVersion: v1
kind: Service
metadata:
  name: scheduler-optimizer-service
  namespace: hpc-system
  labels:
    app: scheduler-optimizer
spec:
  selector:
    app: scheduler-optimizer
  ports:
  - protocol: TCP
    port: 8002
    targetPort: 8002
    name: http
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: scheduler-optimizer-hpa
  namespace: hpc-system
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: scheduler-optimizer
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
